### ISSUE TITLE
Update js-project.sh

### ISSUE THREAD

**Issue by GorskiAnthony** [WildCodeSchool/vps-traefik-starter-kit#8]
Hello 👋 !

Il se trouve qu'en prod, l'ajout de `-backend` nous cause pas mal de soucis...

```diff
- VITE_BACKEND_URL="https://$PROJECT_NAME-backend.$HOST"
+ VITE_BACKEND_URL="https://$PROJECT_NAME.$HOST"
```

D'ailleurs, je ne sais même pas si c'est utile, mais pour nos projets 3 (Promo **SEPT 2023**) nous avons modifié nos `docker-compose.prod.yml` avec `VITE_BACKEND_URL: ""` Et ça fonctionne...

Voilà ! 

https://github.com/WildCodeSchool/vps-traefik-starter-kit/blob/dcd33436aba228f3df69e29ff27c0f5605816fb2/deploy/js-project.sh#L36C55-L36C55

**Comment by jeanfrancois-morin** [comment]
Yes !
Fixed with #9 😉
